### ISSUE TITLE
Adapting to RTSPToWeb

### ISSUE THREAD

**Issue by bulburDE** [Anonym-tsk/MMM-HomeAssistant-WebRTC#4]
There is now an [RTSPtoWebRTC ](https://www.home-assistant.io/integrations/rtsp_to_webrtc/)integration in core which relies on the [RTSPtoWeb](https://github.com/deepch/RTSPtoWeb) service which is also available as an [addon](https://community.home-assistant.io/t/add-on-rtsptoweb-and-rtsptowebrtc/387846) in HACS.
It looks to me like this is the official solution which will probably be better supported in HA than AlexxIT/WebRTC.
Do you have any plans to adapt this plugin so that it will work with RTSPtoWeb?

**Comment by thundergreen** [comment]
#1! Using also new integration. would be nice if it could be ported to it

fir now I get this error:

```
[02.04.2022 00:39.32.599] [ERROR] MMM-HomeAssistant-WebRTC ERROR: Error: Response is not ok
    at /magicmirror2/modules/MMM-HomeAssistant-WebRTC/node_helper.js:27:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by thundergreen** [comment]
any news here?

**Comment by shbatm** [comment]
@thundergreen, I have a working version that connects directly to an RTSPtoWeb server. When I get a chance this week I'll upload it.

**Comment by thundergreen** [comment]
@shbatm  that would be awesome 😍

**Comment by shbatm** [comment]
@thundergreen Try here: https://github.com/shbatm/MMM-RTSPtoWeb
